import { PTYDefinition } from './types';

export const PTY_LIST: PTYDefinition[] = [
  { value: 0, label: "None / Undefined" },
  { value: 31, label: "Alarm" },
  { value: 30, label: "Alarm Test" },
  { value: 18, label: "Children's programmes" },
  { value: 25, label: "Country Music" },
  { value: 7, label: "Culture / Arts" },
  { value: 2, label: "Current Affairs" },
  { value: 29, label: "Documentary" },
  { value: 6, label: "Drama" },
  { value: 12, label: "Easy Listening Music" },
  { value: 5, label: "Education" },
  { value: 17, label: "Finance / Business" },
  { value: 28, label: "Folk Music" },
  { value: 3, label: "Information" },
  { value: 24, label: "Jazz Music / Jazz and Blues" },
  { value: 23, label: "Leisure" },
  { value: 13, label: "Light Classical" },
  { value: 26, label: "National Music" },
  { value: 1, label: "News" },
  { value: 27, label: "Oldies Music" },
  { value: 15, label: "Other Music" },
  { value: 21, label: "Phone In" },
  { value: 10, label: "Pop Music" },
  { value: 20, label: "Religion" },
  { value: 11, label: "Rock Music" },
  { value: 8, label: "Science" },
  { value: 14, label: "Serious Classical" },
  { value: 19, label: "Social Affairs / Factual" },
  { value: 4, label: "Sport" },
  { value: 22, label: "Travel" },
  { value: 9, label: "Varied Speech / Talk" },
  { value: 16, label: "Weather / Meteorology" },
];

export const BITRATES_KBPS = [
  32, 40, 48, 56, 64, 72, 80, 88, 96, 112, 128, 160, 192, 224, 256, 320, 384
];

export const MAX_CU = 864;

export interface CodeDefinition {
  code: string;
  name: string;
}

export const COUNTRIES: CodeDefinition[] = [
    { name: "None / Undefined", code: "00" },
    { name: "Afghanistan", code: "F0" },
    { name: "Albania", code: "E0" },
    { name: "Algeria", code: "E0" },
    { name: "Andorra", code: "E0" },
    { name: "Angola", code: "D0" },
    { name: "Argentina", code: "A2" },
    { name: "Armenia", code: "E4" },
    { name: "Australia", code: "E0" },
    { name: "Austria", code: "E0" },
    { name: "Azerbaijan", code: "E3" },
    { name: "Azores", code: "E0" },
    { name: "Bahamas", code: "A2" },
    { name: "Bahrain", code: "F0" },
    { name: "Bangladesh", code: "F1" },
    { name: "Barbados", code: "A2" },
    { name: "Belarus", code: "E3" },
    { name: "Belgium", code: "E0" },
    { name: "Belize", code: "A2" },
    { name: "Benin", code: "D0" },
    { name: "Bermuda", code: "A2" },
    { name: "Bhutan", code: "F1" },
    { name: "Bolivia", code: "A3" },
    { name: "Bosnia and Herzegovina", code: "E4" },
    { name: "Botswana", code: "D1" },
    { name: "Brazil", code: "A2" },
    { name: "Bulgaria", code: "E1" },
    { name: "Burundi", code: "D1" },
    { name: "Cambodia", code: "F2" },
    { name: "Cameroon", code: "D0" },
    { name: "Canada", code: "A1" },
    { name: "Canary Islands", code: "E0" },
    { name: "Cape Verde", code: "D1" },
    { name: "Chad", code: "D2" },
    { name: "Chile", code: "A3" },
    { name: "China", code: "F0" },
    { name: "Colombia", code: "A3" },
    { name: "Costa Rica", code: "A2" },
    { name: "Croatia", code: "E3" },
    { name: "Cuba", code: "A2" },
    { name: "Cyprus", code: "E1" },
    { name: "Czech Republic", code: "E2" },
    { name: "Denmark", code: "E1" },
    { name: "Djibouti", code: "D0" },
    { name: "Dominican Republic", code: "A3" },
    { name: "Ecuador", code: "A2" },
    { name: "Egypt", code: "E0" },
    { name: "El Salvador", code: "A4" },
    { name: "Estonia", code: "D0" },
    { name: "Ethiopia", code: "D1" },
    { name: "Eswatini", code: "D2" },
    { name: "Faroe Islands", code: "E1" },
    { name: "Fiji", code: "F1" },
    { name: "Finland", code: "E1" },
    { name: "France", code: "E1" },
    { name: "Georgia", code: "E4" },
    { name: "Germany", code: "E0" },
    { name: "Gibraltar", code: "E1" },
    { name: "Greece", code: "E1" },
    { name: "Greenland", code: "A1" },
    { name: "Grenada", code: "A3" },
    { name: "Guadeloupe", code: "A2" },
    { name: "Guatemala", code: "A4" },
    { name: "Guinea", code: "D0" },
    { name: "Guyana", code: "A3" },
    { name: "Haiti", code: "A4" },
    { name: "Hong Kong", code: "F1" },
    { name: "Hungary", code: "E0" },
    { name: "Iceland", code: "E2" },
    { name: "India", code: "F2" },
    { name: "Indonesia", code: "F2" },
    { name: "Iran", code: "F1" },
    { name: "Iraq", code: "E1" },
    { name: "Ireland", code: "E3" },
    { name: "Israel", code: "E0" },
    { name: "Italy", code: "E0" },
    { name: "Jamaica", code: "A3" },
    { name: "Japan", code: "F2" },
    { name: "Jordan", code: "E1" },
    { name: "Kazakhstan", code: "E3" },
    { name: "Kenya", code: "D2" },
    { name: "Kiribati", code: "F1" },
    { name: "Kosovo", code: "E4" },
    { name: "Kuwait", code: "F2" },
    { name: "Kyrgyzstan", code: "E4" },
    { name: "Laos", code: "F3" },
    { name: "Latvia", code: "E3" },
    { name: "Lebanon", code: "E3" },
    { name: "Libya", code: "E1" },
    { name: "Liechtenstein", code: "E2" },
    { name: "Lithuania", code: "E2" },
    { name: "Luxembourg", code: "E1" },
    { name: "Macau", code: "F2" },
    { name: "Madagascar", code: "D0" },
    { name: "Malawi", code: "D0" },
    { name: "Malaysia", code: "F0" },
    { name: "Maldives", code: "F2" },
    { name: "Malta", code: "E0" },
    { name: "Mauritius", code: "D3" },
    { name: "Mexico", code: "A4" },
    { name: "Moldova", code: "E4" },
    { name: "Monaco", code: "E2" },
    { name: "Mongolia", code: "F3" },
    { name: "Montenegro", code: "E3" },
    { name: "Morocco", code: "E2" },
    { name: "Mozambique", code: "D2" },
    { name: "Myanmar", code: "F0" },
    { name: "Namibia", code: "D1" },
    { name: "Nauru", code: "F1" },
    { name: "Nepal", code: "F2" },
    { name: "Netherlands", code: "E3" },
    { name: "Netherlands Antilles", code: "A2" },
    { name: "New Zealand", code: "F1" },
    { name: "North Korea", code: "F0" },
    { name: "North Macedonia", code: "E3" },
    { name: "Norway", code: "E2" },
    { name: "Oman", code: "F1" },
    { name: "Pakistan", code: "F1" },
    { name: "Palestine", code: "E0" },
    { name: "Panama", code: "A3" },
    { name: "Papua New Guinea", code: "F3" },
    { name: "Paraguay", code: "A3" },
    { name: "Peru", code: "A4" },
    { name: "Philippines", code: "F2" },
    { name: "Poland", code: "E2" },
    { name: "Portugal", code: "E4" },
    { name: "Puerto Rico", code: "A3" },
    { name: "Qatar", code: "F2" },
    { name: "Romania", code: "E1" },
    { name: "Russia", code: "E0" },
    { name: "Saint Kitts and Nevis", code: "A4" },
    { name: "Saint Lucia", code: "A4" },
    { name: "Saint-Pierre-et-Miquelon", code: "A6" },
    { name: "Saint-Vincent", code: "A5" },
    { name: "San Marino", code: "E1" },
    { name: "Saudi Arabia", code: "F0" },
    { name: "Senegal", code: "D1" },
    { name: "Serbia", code: "E2" },
    { name: "Seychelles", code: "D3" },
    { name: "Sierra Leone", code: "D2" },
    { name: "Singapore", code: "F2" },
    { name: "Slovakia", code: "E2" },
    { name: "Slovenia", code: "E4" },
    { name: "Solomon Islands", code: "F1" },
    { name: "Somalia", code: "D2" },
    { name: "South Africa", code: "D0" },
    { name: "South Korea", code: "F1" },
    { name: "Spain", code: "E2" },
    { name: "Sri Lanka", code: "F1" },
    { name: "Sudan", code: "D3" },
    { name: "Sweden", code: "E3" },
    { name: "Switzerland", code: "E1" },
    { name: "Syria", code: "E2" },
    { name: "Taiwan", code: "F1" },
    { name: "Tajikistan", code: "E3" },
    { name: "Thailand", code: "F3" },
    { name: "Togo", code: "D0" },
    { name: "Tonga", code: "F3" },
    { name: "Tunisia", code: "E2" },
    { name: "Turkey", code: "E3" },
    { name: "Turkmenistan", code: "E4" },
    { name: "Uganda", code: "D2" },
    { name: "Ukraine", code: "E4" },
    { name: "United Arab Emirates", code: "F2" },
    { name: "United Kingdom", code: "E1" },
    { name: "United States of America (USA)", code: "A0" },
    { name: "Uruguay", code: "A4" },
    { name: "Uzbekistan", code: "E4" },
    { name: "Vanuatu", code: "F2" },
    { name: "Vatican", code: "E2" },
    { name: "Venezuela", code: "A4" },
    { name: "Virgin Islands", code: "A5" },
    { name: "Western Sahara", code: "D3" },
    { name: "Zambia", code: "D2" },
    { name: "Zanzibar", code: "D2" },
    { name: "Zimbabwe", code: "D2" },
];

export const LANGUAGES: CodeDefinition[] = [
    { name: "None / Undefined", code: "00" },
    { name: "Albanian", code: "01" },
    { name: "Amharic", code: "7F" },
    { name: "Arabic", code: "7E" },
    { name: "Armenian", code: "7D" },
    { name: "Assamese", code: "7C" },
    { name: "Azerbaijani", code: "7B" },
    { name: "Bambara", code: "7A" },
    { name: "Basque", code: "0D" },
    { name: "Belarusian", code: "79" },
    { name: "Bengali", code: "78" },
    { name: "Breton", code: "02" },
    { name: "Bulgarian", code: "77" },
    { name: "Burmese", code: "76" },
    { name: "Catalan", code: "03" },
    { name: "Chinese", code: "75" },
    { name: "Chuvash", code: "74" },
    { name: "Croatian", code: "04" },
    { name: "Czech", code: "06" },
    { name: "Danish", code: "07" },
    { name: "Dari", code: "73" },
    { name: "Dutch", code: "1D" },
    { name: "English", code: "09" },
    { name: "Esperanto", code: "0B" },
    { name: "Estonian", code: "0C" },
    { name: "Faroese", code: "0E" },
    { name: "Finnish", code: "27" },
    { name: "Flemish", code: "2A" },
    { name: "French", code: "0F" },
    { name: "Frisian", code: "10" },
    { name: "Fulani", code: "72" },
    { name: "Gaelic", code: "12" },
    { name: "Galician", code: "13" },
    { name: "Georgian", code: "71" },
    { name: "German", code: "08" },
    { name: "Greek", code: "70" },
    { name: "Gujarati", code: "6F" },
    { name: "Gurani", code: "6E" },
    { name: "Hausa", code: "6D" },
    { name: "Hebrew", code: "6C" },
    { name: "Hindi", code: "6B" },
    { name: "Hungarian", code: "1B" },
    { name: "Icelandic", code: "14" },
    { name: "Indonesian", code: "6A" },
    { name: "Irish", code: "11" },
    { name: "Italian", code: "15" },
    { name: "Japanese", code: "69" },
    { name: "Kannada", code: "68" },
    { name: "Kazakh", code: "67" },
    { name: "Khmer", code: "66" },
    { name: "Korean", code: "65" },
    { name: "Laotian", code: "64" },
    { name: "Latin", code: "17" },
    { name: "Latvian", code: "18" },
    { name: "Lithuanian", code: "1A" },
    { name: "Luxembourgish", code: "19" },
    { name: "Macedonian", code: "63" },
    { name: "Malagasy", code: "62" },
    { name: "Malaysian", code: "61" },
    { name: "Maltese", code: "1C" },
    { name: "Marathi", code: "5F" },
    { name: "Moldavian", code: "60" },
    { name: "Ndebele", code: "5E" },
    { name: "Nepali", code: "5D" },
    { name: "Norwegian", code: "1E" },
    { name: "Occitan", code: "1F" },
    { name: "Oriya", code: "5C" },
    { name: "Papiamento", code: "5B" },
    { name: "Persian", code: "5A" },
    { name: "Polish", code: "20" },
    { name: "Portuguese", code: "21" },
    { name: "Punjabi", code: "59" },
    { name: "Pushtu", code: "58" },
    { name: "Quechua", code: "57" },
    { name: "Romanian", code: "22" },
    { name: "Romansh", code: "23" },
    { name: "Russian", code: "56" },
    { name: "Rusyn", code: "55" },
    { name: "Sami", code: "16" },
    { name: "Serbian", code: "24" },
    { name: "Serbo-Croat", code: "54" },
    { name: "Shona", code: "53" },
    { name: "Sinhalese", code: "52" },
    { name: "Slovak", code: "25" },
    { name: "Slovenian", code: "26" },
    { name: "Somali", code: "51" },
    { name: "Spanish", code: "0A" },
    { name: "Sranan Tongo", code: "50" },
    { name: "Swahili", code: "4F" },
    { name: "Swedish", code: "28" },
    { name: "Tajik", code: "4E" },
    { name: "Tamil", code: "4D" },
    { name: "Tatar", code: "4C" },
    { name: "Telugu", code: "4B" },
    { name: "Thai", code: "4A" },
    { name: "Turkish", code: "29" },
    { name: "Ukrainian", code: "49" },
    { name: "Urdu", code: "48" },
    { name: "Uzbek", code: "47" },
    { name: "Vietnamese", code: "46" },
    { name: "Walloon", code: "2B" },
    { name: "Zulu", code: "45" },
];